module.exports.authService = require('./auth.service');
// module.exports.emailService = require('./email.service');
module.exports.tokenService = require('./token.service');
module.exports.userService = require('./user.service');
module.exports.soudhaPartnerService = require('./soudha/soudhaPartner.service');
module.exports.bookedConsignmentService = require('./soudha/bookedConsignment.service');
module.exports.receivedConsignmentService = require('./soudha/receivedConsignment.service');
module.exports.oilTypeService = require('./soudha/oilType.service');
module.exports.otpService = require('./otp.service');
